Name = input("Enter your name : ")
Branch = input("Enter your branch : ")
Gender = input("Enter your gender : ")
College = input("Enter your college name : ")
Age = int(input("Enter your age : "))

print("Name :",Name)
print("Branch :",Branch)
print("Gender :",Gender)
print("College :",College)
print("Age :",Age)
